# Generated by Django 5.2.6 on 2025-10-13 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFixture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('league_competition', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(max_length=500)),
                ('article_type', models.CharField(choices=[('news', 'News'), ('fixture', 'Fixture'), ('result', 'Result'), ('analysis', 'Analysis')], default='news', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('publish_date', models.DateTimeField()),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=20)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'ordering': ['-subscription_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('html_template', models.TextField()),
                ('css_styles', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('soccer', 'Soccer'), ('rugby', 'Rugby'), ('formula1', 'Formula 1'), ('boxing', 'Boxing'), ('tennis', 'Tennis'), ('golf', 'Golf'), ('darts', 'Darts'), ('chess', 'Chess')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('edition_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_subscribers', models.IntegerField(default=0)),
                ('template_data', models.JSONField(blank=True, default=dict)),
                ('articles', models.ManyToManyField(blank=True, related_name='newsletters', to='core.newsarticle')),
                ('featured_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_newsletters', to='core.newsarticle')),
                ('fixtures', models.ManyToManyField(blank=True, related_name='newsletters', to='core.matchfixture')),
            ],
            options={
                'ordering': ['-edition_date'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sport_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportcategory'),
        ),
        migrations.AddField(
            model_name='matchfixture',
            name='sport_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportcategory'),
        ),
        migrations.CreateModel(
            name='NewsletterDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_links', models.JSONField(blank=True, default=list)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newslettersubscriber')),
            ],
            options={
                'unique_together': {('newsletter', 'subscriber')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='newsarticle',
            unique_together={('title', 'source_url')},
        ),
    ]
