# Generated by Django 5.2.6 on 2025-10-13 22:16

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_callbackrequest_contactmessage_eventbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_subscribers', models.IntegerField(default=0)),
                ('new_subscriptions', models.IntegerField(default=0)),
                ('unsubscriptions', models.IntegerField(default=0)),
                ('active_subscribers', models.IntegerField(default=0)),
                ('growth_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='newsletterdelivery',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsletterdelivery',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailClickTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('clicked_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newsletterdelivery')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('total_bounced', models.IntegerField(default=0)),
                ('unique_opens', models.IntegerField(default=0)),
                ('unique_clicks', models.IntegerField(default=0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('delivery_rate', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.newsletter')),
            ],
            options={
                'ordering': ['-newsletter__edition_date'],
            },
        ),
        migrations.CreateModel(
            name='SportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subscriber_count', models.IntegerField(default=0)),
                ('article_count', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('sport_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportcategory')),
            ],
            options={
                'ordering': ['-date', 'sport_category'],
                'unique_together': {('date', 'sport_category')},
            },
        ),
    ]
