# Generated by Django 5.2.6 on 2025-10-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_subscriberanalytics_newsletterdelivery_click_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.CharField(max_length=800),
        ),
    ]
