# Generated by Django 5.2.6 on 2025-10-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_newsarticle_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="link_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
