# Generated by Django 5.2.6 on 2025-10-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_newsarticle_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="template_used",
            field=models.CharField(blank=True, default="default", max_length=100),
        ),
    ]
